name: Excercise 3
on:
  - push
jobs:
  excercise_matrix:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12' ]
        platform: ['ubuntu-22.4']
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - name: "Setting up Python ${{matrix.python-version}}" 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python3 --version







    steps:
      - uses: actions/checkout@v4
      - name: "setting up Python version 3.12 for githib exercise 2"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python3 --version
